Development
Technyen/StoriesAppBack pull request #6
Opened 2023-09-25 17:28 UTC by Technyen

2023-09-29 18:27 UTC, Technyen commented
up-to-date

2023-10-02 14:19 UTC, elias-rod commented on Api/.config/dotnet-tools.json
Remove this file

2023-10-02 14:44 UTC, elias-rod requested changes

2023-10-02 14:44 UTC, elias-rod commented on Api/.config/dotnet-tools.json
Remove this file

2023-10-02 14:44 UTC, elias-rod commented on Api/Controllers/StoryController.cs
>          [HttpGet("getAll")]
Resolve all warnings

2023-10-02 14:44 UTC, elias-rod commented on Api/Controllers/StoryController.cs
> +
Remove this and all unnecessary whitespace.

2023-10-02 14:44 UTC, elias-rod commented on Api/Entities/Story.cs
> +        public string? ImageUrl { get; set; }
Remove null conditional operator from all models and entities that must have a value, the ones that can have a value optionally, could use the operator.

2023-10-02 14:44 UTC, elias-rod commented on Api/Program.cs
> +            //BlobStorage
Remove unnecessary comments everywhere.

2023-10-02 14:44 UTC, elias-rod commented on Api/Properties/PublishProfiles/Api20230927150307 - Web Deploy.pubxml
>  </Project>
Add a new line at the end of all files.

2023-10-02 14:44 UTC, elias-rod commented on Api/Services/BlobStorageService.cs
> +	{
Fix all files indentation.

2023-10-02 14:44 UTC, elias-rod commented on Api/Services/StoryService.cs
> +                await _cosmosService.UpdateItemAsync(story, story.Id);
Update the flow to consider in the EditStoryModel the ImageUrl.

2023-10-02 14:44 UTC, elias-rod commented on ApiTest/UnitTest1.cs
>  using Api.Entities;
Rename file to reflect what part of the application is testing something like StoryServiceTest

2023-10-02 14:44 UTC, elias-rod commented on ApiTest/UnitTest1.cs
>          public async void TestGetStories()
Rename to GetStoriesAsyncReturnStories

2023-10-02 14:44 UTC, elias-rod commented on ApiTest/UnitTest1.cs
>              // Assert
Evaluate Usings file and remove if neccessary.

2023-10-03 19:38 UTC, elias-rod approved these changes

2023-10-03 19:38 UTC, elias-rod commented on Api/Services/CosmosService.cs
> +        public async Task<ItemResponse<T>> DeleteItemAsync<T>(string? itemId, string partitionKey)
Remove null operator

2023-10-04 12:50 UTC, merged